#ifndef POKEMON_BIOS_H
#define POKEMON_BIOS_H

#include <global.h>

struct Attest;
struct BasisStatus;
struct ExpandStatus;
struct Pokemon;
union Ribbon;
struct Sinka;
struct PokemonData;
struct PokemonDataCgData;
struct PokemonDataWaza;
struct PokemonWaza;
typedef struct PokemonGrowDataBios PokemonGrowDataBios;
typedef struct PokemonSeikakuDataBios PokemonSeikakuDataBios;
typedef struct PokemonSeikakuRateBios PokemonSeikakuRateBios;

extern "C" u32 pokemonSeikakuRateDataBiosGetWaru(PokemonSeikakuRateBios*);
extern "C" u32 pokemonSeikakuRateDataBiosGetKake(PokemonSeikakuRateBios*);
extern "C" PokemonSeikakuRateBios* pokemonSeikakuRateDataBiosGetPtr(u32);
extern "C" u32 pokemonSeikakuDataBiosGetNimblenessRateDataId(PokemonSeikakuDataBios*);
extern "C" u32 pokemonSeikakuDataBiosGetSpeDefRateDataId(PokemonSeikakuDataBios*);
extern "C" u32 pokemonSeikakuDataBiosGetSpeAtkRateDataId(PokemonSeikakuDataBios*);
extern "C" u32 pokemonSeikakuDataBiosGetPhyDefRateDataId(PokemonSeikakuDataBios*);
extern "C" u32 pokemonSeikakuDataBiosGetPhyAtkRateDataId(PokemonSeikakuDataBios*);
extern "C" PokemonSeikakuDataBios* pokemonSeikakuDataBiosGetPtr(u32);
extern "C" PokemonGrowDataBios* pokemonGrowDataBiosGetPtr(u8);
extern "C" int pokemonGrowDataBiosGetExp(PokemonGrowDataBios*, unsigned char);

extern "C" {
void pokemonBiosSetEventGetFlag(Pokemon*, u32);
void pokemonBiosSetFightTrainerPokemonDataId(Pokemon*, u16);
void pokemonBiosSetPara1Amari(Pokemon*, u16);
void pokemonBiosSetAmari(Pokemon*, u16);
void pokemonBiosSetMailId(Pokemon*, u8);
void pokemonBiosSetPcboxMark(Pokemon*, u8);
void pokemonBiosSetFlagAmari(Pokemon*, u8);
void pokemonBiosSetFuseiFlag(Pokemon*, bool);
void pokemonBiosSetTokuseiFlag(Pokemon*, bool);
void pokemonBiosSetTamagoFlag(Pokemon*, bool);
void pokemonBiosSetPokerus(Pokemon*, u8);
void pokemonBiosSetAmariRibbon(Pokemon*, u8);
void pokemonBiosSetWorldRibbon(Pokemon*, u8);
void pokemonBiosSetEarthRibbon(Pokemon*, u8);
void pokemonBiosSetNationalRibbon(Pokemon*, u8);
void pokemonBiosSetCountryRibbon(Pokemon*, u8);
void pokemonBiosSetSkyRibbon(Pokemon*, u8);
void pokemonBiosSetLandRibbon(Pokemon*, u8);
void pokemonBiosSetMarineRibbon(Pokemon*, u8);
void pokemonBiosSetGanbaRibbon(Pokemon*, u8);
void pokemonBiosSetBromideRibbon(Pokemon*, u8);
void pokemonBiosSetVictoryRibbon(Pokemon*, u8);
void pokemonBiosSetWinningRibbon(Pokemon*, u8);
void pokemonBiosSetChampRibbon(Pokemon*, u8);
void pokemonBiosSetFur(Pokemon*, u8);
void pokemonBiosSetStrongMedal(Pokemon*, u8);
void pokemonBiosSetCleverMedal(Pokemon*, u8);
void pokemonBiosSetCuteMedal(Pokemon*, u8);
void pokemonBiosSetBeautifulMedal(Pokemon*, u8);
void pokemonBiosSetStyleMedal(Pokemon*, u8);
void pokemonBiosSetStrong(Pokemon*, u8);
void pokemonBiosSetClever(Pokemon*, u8);
void pokemonBiosSetCute(Pokemon*, u8);
void pokemonBiosSetBeautiful(Pokemon*, u8);
void pokemonBiosSetStyle(Pokemon*, u8);
void pokemonBiosSetDp(Pokemon*, s32);
void pokemonBiosSetDarkpokemonDataId(Pokemon*, u16);
void pokemonBiosSetFriend(Pokemon*, u16);
void pokemonBiosSetNimblenessRnd(Pokemon*, u16);
void pokemonBiosSetSpeDefRnd(Pokemon*, u16);
void pokemonBiosSetSpeAtkRnd(Pokemon*, u16);
void pokemonBiosSetPhyDefRnd(Pokemon*, u16);
void pokemonBiosSetPhyAtkRnd(Pokemon*, u16);
void pokemonBiosSetMaxHpRnd(Pokemon*, u16);
void pokemonBiosSetNimblenessEffort(Pokemon*, u16);
void pokemonBiosSetSpeDefEffort(Pokemon*, u16);
void pokemonBiosSetSpeAtkEffort(Pokemon*, u16);
void pokemonBiosSetPhyDefEffort(Pokemon*, u16);
void pokemonBiosSetPhyAtkEffort(Pokemon*, u16);
void pokemonBiosSetMaxHpEffort(Pokemon*, u16);
void pokemonBiosSetNimbleness(Pokemon*, u16);
void pokemonBiosSetSpeDef(Pokemon*, u16);
void pokemonBiosSetSpeAtk(Pokemon*, u16);
void pokemonBiosSetPhyDef(Pokemon*, u16);
void pokemonBiosSetPhyAtk(Pokemon*, u16);
void pokemonBiosSetMaxHp(Pokemon*, u16);
void pokemonBiosSetHp(Pokemon*, s16);
void pokemonBiosSetItemDataId(Pokemon*, u16);
void pokemonBiosSetPokemonWazaPpCount(Pokemon*, u32, u8);
void pokemonBiosSetPokemonWazaPp(Pokemon*, u32, u8);
void pokemonBiosSetPokemonWazaDataId(Pokemon*, u32, u32);
void pokemonBiosSetConditionAmari(Pokemon*, u32);
void pokemonBiosSetLevel(Pokemon*, u8);
void pokemonBiosSetPoolFriend(Pokemon*, u16);
void pokemonBiosSetPoolExp(Pokemon*, u32);
void pokemonBiosSetExp(Pokemon*, u32);
void pokemonBiosSetNicknameOrgPtr(Pokemon*, void*);
void pokemonBiosSetNicknamePtr(Pokemon*, void*);
void pokemonBiosSetCatchTrainerNamePtr(Pokemon*, void*);
void pokemonBiosSetCatchTrainerRnd(Pokemon*, u32);
void pokemonBiosSetCatchTrainerSex(Pokemon*, u8);
void pokemonBiosSetCatchBallId(Pokemon*, u8);
void pokemonBiosSetCatchLevel(Pokemon*, u8);
void pokemonBiosSetCatchFloorId(Pokemon*, u16);
void pokemonBiosSetRnd(Pokemon*, u32);
void pokemonBiosSetPokemonDataId(Pokemon*, u16);
u16 pokemonDataBiosGetKowaza(PokemonData*, u16);
u32 pokemonDataBiosGetPkxDataId(PokemonData*);
u16 pokemonDataBiosGetNumPokemon(PokemonData*);
u16 pokemonDataBiosGetNumZukan(PokemonData*);
bool pokemonDataBiosGetTukamaetaFlag(PokemonData*);
bool pokemonDataBiosGetMitaFlag(PokemonData*);
u16 pokemonDataBiosGetVoice(PokemonData*);
u32 pokemonDataBiosGetDoc(PokemonData*);
u16 pokemonDataBiosGetWeight(PokemonData*);
u16 pokemonDataBiosGetHeight(PokemonData*);
u32 pokemonDataBiosGetTypeName(PokemonData*);
u8 pokemonDataBiosGetColor(PokemonData*, u16);
u16 pokemonDataBiosGetStatusFaceMenuSpriteId(PokemonData*, u16);
u32 pokemonDataBiosGetPokebodyId(PokemonData*, u16);
PokemonDataCgData* pokemonDataBiosGetCgDataPtr(PokemonData*, u16);
bool pokemonDataBiosGetWazaMcn(PokemonData*, u16);
u16 pokemonDataBiosGetGetWazaDataId(PokemonData*, u16);
u8 pokemonDataBiosGetGetWazaLevel(PokemonData*, u16);
PokemonDataWaza* pokemonDataBiosGetGetWazaPtr(PokemonData*, u16);
u16 pokemonDataBiosGetSinkaPokemonDataId(PokemonData*, u16);
u16 pokemonDataBiosGetSinkaBuff(PokemonData*, u16);
u8 pokemonDataBiosGetSinkaKind(PokemonData*, u16);
Sinka* pokemonDataBiosGetSinkaPtr(PokemonData*, u16);
u8 pokemonDataBiosGetTokuseiDataId(PokemonData*, u16);
u8 pokemonDataBiosGetZokuseiDataId(PokemonData*, u16);
u16 pokemonDataBiosGetItemDataId(PokemonData*, u16);
u16 pokemonDataBiosGetInitFriend(PokemonData*);
u8 pokemonDataBiosGetSexRatio(PokemonData*);
u8 pokemonDataBiosGetGet(PokemonData*);
u8 pokemonDataBiosGetGrowDataId(PokemonData*);
u16 pokemonDataBiosGetGiveExp(PokemonData*);
u16 pokemonDataBiosGetGiveNimblenessEffort(PokemonData*);
u16 pokemonDataBiosGetGiveSpeDefEffort(PokemonData*);
u16 pokemonDataBiosGetGiveSpeAtkEffort(PokemonData*);
u16 pokemonDataBiosGetGivePhyDefEffort(PokemonData*);
u16 pokemonDataBiosGetGivePhyAtkEffort(PokemonData*);
u16 pokemonDataBiosGetGiveMaxHpEffort(PokemonData*);
u16 pokemonDataBiosGetBasisNimbleness(PokemonData*);
u16 pokemonDataBiosGetBasisSpeDef(PokemonData*);
u16 pokemonDataBiosGetBasisSpeAtk(PokemonData*);
u16 pokemonDataBiosGetBasisPhyDef(PokemonData*);
u16 pokemonDataBiosGetBasisPhyAtk(PokemonData*);
u16 pokemonDataBiosGetBasisMaxHp(PokemonData*);
const BasisStatus* pokemonDataBiosGetBasisStatusPtr(PokemonData*, u16);
const char* pokemonDataBiosGetName(PokemonData*);
PokemonData* pokemonDataBiosGetPtr(u16);
u8 pokemonBiosGetEventGetFlag(Pokemon*);
u16 pokemonBiosGetFightTrainerPokemonDataId(Pokemon*);
u16 pokemonBiosGetPara1Amari(Pokemon*);
u16 pokemonBiosGetAmari(Pokemon*);
u8 pokemonBiosGetMailId(Pokemon*);
u8 pokemonBiosGetPcboxMark(Pokemon*);
u8 pokemonBiosGetFlagAmari(Pokemon*);
u8 pokemonBiosGetFuseiFlag(Pokemon*);
u8 pokemonBiosGetTokuseiFlag(Pokemon*);
u8 pokemonBiosGetTamagoFlag(Pokemon*);
u8 pokemonBiosGetPokerus(Pokemon*);
u8 pokemonBiosGetAmariRibbon(Pokemon*);
u8 pokemonBiosGetWorldRibbon(Pokemon*);
u8 pokemonBiosGetEarthRibbon(Pokemon*);
u8 pokemonBiosGetNationalRibbon(Pokemon*);
u8 pokemonBiosGetCountryRibbon(Pokemon*);
u8 pokemonBiosGetSkyRibbon(Pokemon*);
u8 pokemonBiosGetLandRibbon(Pokemon*);
u8 pokemonBiosGetMarineRibbon(Pokemon*);
u8 pokemonBiosGetGanbaRibbon(Pokemon*);
u8 pokemonBiosGetBromideRibbon(Pokemon*);
u8 pokemonBiosGetVictoryRibbon(Pokemon*);
u8 pokemonBiosGetWinningRibbon(Pokemon*);
u8 pokemonBiosGetChampRibbon(Pokemon*);
Ribbon* pokemonBiosGetRibbonPtr(Pokemon*);
u8 pokemonBiosGetFur(Pokemon*);
u8 pokemonBiosGetStrongMedal(Pokemon*);
u8 pokemonBiosGetCleverMedal(Pokemon*);
u8 pokemonBiosGetCuteMedal(Pokemon*);
u8 pokemonBiosGetBeautifulMedal(Pokemon*);
u8 pokemonBiosGetStyleMedal(Pokemon*);
u8 pokemonBiosGetStrong(Pokemon*);
u8 pokemonBiosGetClever(Pokemon*);
u8 pokemonBiosGetCute(Pokemon*);
u8 pokemonBiosGetBeautiful(Pokemon*);
u8 pokemonBiosGetStyle(Pokemon*);
ExpandStatus* pokemonBiosGetExpandStatusPtr(Pokemon*, u16);
u8 pokemonBiosGetInitDp(Pokemon*);
u8 pokemonBiosGetDarkFlag(Pokemon*);
u8 pokemonBiosGetPoolFriend(Pokemon*);
u8 pokemonBiosGetPoolExp(Pokemon*);
u8 pokemonBiosGetDp(Pokemon*);
u16 pokemonBiosGetDarkpokemonDataId(Pokemon*);
u16 pokemonBiosGetFriend(Pokemon*);
u8 pokemonBiosGetNimblenessRnd(Pokemon*);
u8 pokemonBiosGetSpeDefRnd(Pokemon*);
u8 pokemonBiosGetSpeAtkRnd(Pokemon*);
u8 pokemonBiosGetPhyDefRnd(Pokemon*);
u8 pokemonBiosGetPhyAtkRnd(Pokemon*);
u8 pokemonBiosGetMaxHpRnd(Pokemon*);
u16 pokemonBiosGetNimblenessEffort(Pokemon*);
u16 pokemonBiosGetSpeDefEffort(Pokemon*);
u16 pokemonBiosGetSpeAtkEffort(Pokemon*);
u16 pokemonBiosGetPhyDefEffort(Pokemon*);
u16 pokemonBiosGetPhyAtkEffort(Pokemon*);
u16 pokemonBiosGetMaxHpEffort(Pokemon*);
u16 pokemonBiosGetNimbleness(Pokemon*);
u16 pokemonBiosGetSpeDef(Pokemon*);
u16 pokemonBiosGetSpeAtk(Pokemon*);
u16 pokemonBiosGetPhyDef(Pokemon*);
u16 pokemonBiosGetPhyAtk(Pokemon*);
u16 pokemonBiosGetMaxHp(Pokemon*);
u16 pokemonBiosGetHp(Pokemon*);
u16 pokemonBiosGetItemDataId(Pokemon*);
u8 pokemonBiosGetPokemonWazaPpCount(Pokemon*, u32);
u8 pokemonBiosGetPokemonWazaPp(Pokemon*, u32);
u16 pokemonBiosGetPokemonWazaDataId(Pokemon*, u32);
PokemonWaza* pokemonBiosGetPokemonWazaPtr(Pokemon*, u32, u8);
u32 pokemonBiosGetConditionAmari(Pokemon*);
u8 pokemonBiosGetLevel(Pokemon*);
u32 pokemonBiosGetExp(Pokemon*);
char* pokemonBiosGetNicknameOrgPtr(Pokemon*);
char* pokemonBiosGetNicknamePtr(Pokemon*);
char* pokemonBiosGetCatchTrainerNamePtr(Pokemon*);
u32 pokemonBiosGetCatchTrainerRnd(Pokemon*);
u8 pokemonBiosGetCatchTrainerSex(Pokemon*);
u8 pokemonBiosGetCatchBallId(Pokemon*);
u8 pokemonBiosGetCatchLevel(Pokemon*);
u16 pokemonBiosGetCatchFloorId(Pokemon*);
Attest* pokemonBiosGetAttest(Pokemon*);
u32 pokemonBiosGetRnd(Pokemon*);
u32 pokemonBiosGetPokemonDataId(Pokemon*);
void pokemonWazaBiosCopy(PokemonWaza*, const PokemonWaza*);
void pokemonBiosCopy(Pokemon*, const Pokemon*);
}

#endif
